/*
 * ● YukkiMusic
 * ○ A high-performance engine for streaming music in Telegram voicechats.
 *
 * Copyright (C) 2026 TheTeamVivek
 *
 * This program is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * Repository: https://github.com/TheTeamVivek/YukkiMusic
 */

package modules

import (
	td "github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/filters/callbackquery"

	"yukkimusic/config"
	"yukkimusic/internal/core"
)

func Init(bot *td.Client, assistants *core.AssistantManager) {
	assistants.ForEach(func(a *core.Assistant) {
		a.Client.UpdatesGetState()
	})

	// td client handlers
	bot.OnCommand("start", WithBlacklistMessage(startHandler))
	bot.OnCommand("help", WithBlacklistMessage(helpHandler))
	bot.OnCommand("ping", WithBlacklistMessage(pingHandler))
	bot.OnCommand("mute", WithBlacklistMessage(muteHandler))
	bot.OnCommand("cmute", WithBlacklistMessage(cmuteHandler))
	bot.OnCommand("unmute", WithBlacklistMessage(unmuteHandler))
	bot.OnCommand("cunmute", WithBlacklistMessage(cunmuteHandler))
	bot.OnCommand("pause", WithBlacklistMessage(pauseHandler))
	bot.OnCommand("cpause", WithBlacklistMessage(cpauseHandler))
	bot.OnCommand("resume", WithBlacklistMessage(resumeHandler))
	bot.OnCommand("cresume", WithBlacklistMessage(cresumeHandler))
	bot.OnCommand("position", WithBlacklistMessage(positionHandler))
	bot.OnCommand("pos", WithBlacklistMessage(positionHandler))
	bot.OnCommand("cposition", WithBlacklistMessage(cpositionHandler))
	bot.OnCommand("cpos", WithBlacklistMessage(cpositionHandler))
	bot.OnCommand("replay", WithBlacklistMessage(replayHandler))
	bot.OnCommand("creplay", WithBlacklistMessage(creplayHandler))
	bot.OnCommand("loop", WithBlacklistMessage(loopHandler))
	bot.OnCommand("setloop", WithBlacklistMessage(loopHandler))
	bot.OnCommand("cloop", WithBlacklistMessage(cloopHandler))
	bot.OnCommand("csetloop", WithBlacklistMessage(cloopHandler))
	bot.OnCommand("speed", WithBlacklistMessage(speedHandler))
	bot.OnCommand("setspeed", WithBlacklistMessage(speedHandler))
	bot.OnCommand("speedup", WithBlacklistMessage(speedHandler))
	bot.OnCommand("cspeed", WithBlacklistMessage(cspeedHandler))
	bot.OnCommand("csetspeed", WithBlacklistMessage(cspeedHandler))
	bot.OnCommand("cspeedup", WithBlacklistMessage(cspeedHandler))
	bot.OnCommand("shuffle", WithBlacklistMessage(shuffleHandler))
	bot.OnCommand("cshuffle", WithBlacklistMessage(cshuffleHandler))
	bot.OnCommand("seek", WithBlacklistMessage(seekHandler))
	bot.OnCommand("cseek", WithBlacklistMessage(cseekHandler))
	bot.OnCommand("seekback", WithBlacklistMessage(seekbackHandler))
	bot.OnCommand("cseekback", WithBlacklistMessage(cseekbackHandler))
	bot.OnCommand("jump", WithBlacklistMessage(jumpHandler))
	bot.OnCommand("cjump", WithBlacklistMessage(cjumpHandler))
	bot.OnCommand("queue", WithBlacklistMessage(queueHandler))
	bot.OnCommand("cqueue", WithBlacklistMessage(cqueueHandler))
	bot.OnCommand("remove", WithBlacklistMessage(removeHandler))
	bot.OnCommand("cremove", WithBlacklistMessage(cremoveHandler))
	bot.OnCommand("clear", WithBlacklistMessage(clearHandler))
	bot.OnCommand("cclear", WithBlacklistMessage(cclearHandler))
	bot.OnCommand("move", WithBlacklistMessage(moveHandler))
	bot.OnCommand("cmove", WithBlacklistMessage(cmoveHandler))
	bot.OnCommand("ac", WithBlacklistMessage(activeHandler))
	bot.OnCommand("active", WithBlacklistMessage(activeHandler))
	bot.OnCommand("activevc", WithBlacklistMessage(activeHandler))
	bot.OnCommand("activevoice", WithBlacklistMessage(activeHandler))
	bot.OnCommand("addsudo", WithBlacklistMessage(handleAddSudo))
	bot.OnCommand("ev", WithBlacklistMessage(evalCommandHandler))
	bot.OnCommand("eval", WithBlacklistMessage(evalCommandHandler))
	bot.OnCommand("sh", WithBlacklistMessage(shellHandler))
	bot.OnCommand("bash", WithBlacklistMessage(shellHandler))
	bot.OnCommand("shell", WithBlacklistMessage(shellHandler))
	bot.OnCommand("json", WithBlacklistMessage(jsonHandle))
	bot.OnCommand("log", WithBlacklistMessage(logsHandler))
	bot.OnCommand("logs", WithBlacklistMessage(logsHandler))
	bot.OnCommand("skip", WithBlacklistMessage(skipHandler))
	bot.OnCommand("cskip", WithBlacklistMessage(cskipHandler))
	bot.OnCommand("play", WithBlacklistMessage(playHandler))
	bot.OnCommand("fplay", WithBlacklistMessage(fplayHandler))
	bot.OnCommand("playforce", WithBlacklistMessage(fplayHandler))
	bot.OnCommand("cfplay", WithBlacklistMessage(cfplayHandler))
	bot.OnCommand("fcplay", WithBlacklistMessage(cfplayHandler))
	bot.OnCommand("cforceplay", WithBlacklistMessage(cfplayHandler))
	bot.OnCommand("cplayforce", WithBlacklistMessage(cfplayHandler))
	bot.OnCommand("vplay", WithBlacklistMessage(vplayHandler))
	bot.OnCommand("fvplay", WithBlacklistMessage(fvplayHandler))
	bot.OnCommand("vfplay", WithBlacklistMessage(fvplayHandler))
	bot.OnCommand("vplayforce", WithBlacklistMessage(fvplayHandler))
	bot.OnCommand("vcplay", WithBlacklistMessage(vcplayHandler))
	bot.OnCommand("cvplay", WithBlacklistMessage(vcplayHandler))
	bot.OnCommand("fvcplay", WithBlacklistMessage(fvcplayHandler))
	bot.OnCommand("vcplayforce", WithBlacklistMessage(fvcplayHandler))
	bot.OnCommand("cplay", WithBlacklistMessage(cplayHandler))
	bot.OnCommand("end", WithBlacklistMessage(stopHandler))
	bot.OnCommand("stop", WithBlacklistMessage(stopHandler))
	bot.OnCommand("cstop", WithBlacklistMessage(cstopHandler))
	bot.OnCommand("cend", WithBlacklistMessage(cstopHandler))
	bot.OnCommand("nothumb", WithBlacklistMessage(nothumbHandler))
	bot.OnCommand("nothumbs", WithBlacklistMessage(nothumbHandler))
	bot.OnCommand("channelplay", WithBlacklistMessage(setCPlayHandler))
	bot.OnCommand("setcplay", WithBlacklistMessage(setCPlayHandler))
	bot.OnCommand("addsudoer", WithBlacklistMessage(handleAddSudo))
	bot.OnCommand("sudoadd", WithBlacklistMessage(handleAddSudo))
	bot.OnCommand("blocked", WithBlacklistMessage(handleBlacklisted))
	bot.OnCommand("blacklisted", WithBlacklistMessage(handleBlacklisted))
	bot.OnCommand("blockchat", WithBlacklistMessage(handleBlockChat))
	bot.OnCommand("blacklistchat", WithBlacklistMessage(handleBlockChat))
	bot.OnCommand("blackchat", WithBlacklistMessage(handleBlockChat))
	bot.OnCommand("blchat", WithBlacklistMessage(handleBlockChat))
	bot.OnCommand("blockuser", WithBlacklistMessage(handleBlockUser))
	bot.OnCommand("blacklistuser", WithBlacklistMessage(handleBlockUser))
	bot.OnCommand("blackuser", WithBlacklistMessage(handleBlockUser))
	bot.OnCommand("bluser", WithBlacklistMessage(handleBlockUser))
	bot.OnCommand("broadcast", WithBlacklistMessage(broadcastHandler))
	bot.OnCommand("gcast", WithBlacklistMessage(broadcastHandler))
	bot.OnCommand("bcast", WithBlacklistMessage(broadcastHandler))
	bot.OnCommand("delsudo", WithBlacklistMessage(handleDelSudo))
	bot.OnCommand("delsudoer", WithBlacklistMessage(handleDelSudo))
	bot.OnCommand("sudodel", WithBlacklistMessage(handleDelSudo))
	bot.OnCommand("remsudo", WithBlacklistMessage(handleDelSudo))
	bot.OnCommand("rmsudo", WithBlacklistMessage(handleDelSudo))
	bot.OnCommand("sudorem", WithBlacklistMessage(handleDelSudo))
	bot.OnCommand("dropsudo", WithBlacklistMessage(handleDelSudo))
	bot.OnCommand("unsudo", WithBlacklistMessage(handleDelSudo))
	bot.OnCommand("lang", WithBlacklistMessage(langHandler))
	bot.OnCommand("language", WithBlacklistMessage(langHandler))
	bot.OnCommand("maintenance", WithBlacklistMessage(handleMaintenance))
	bot.OnCommand("maint", WithBlacklistMessage(handleMaintenance))
	bot.OnCommand("sudoers", WithBlacklistMessage(handleGetSudoers))
	bot.OnCommand("listsudo", WithBlacklistMessage(handleGetSudoers))
	bot.OnCommand("sudolist", WithBlacklistMessage(handleGetSudoers))
	bot.OnCommand("unblockchat", WithBlacklistMessage(handleUnblockChat))
	bot.OnCommand("unblacklistchat", WithBlacklistMessage(handleUnblockChat))
	bot.OnCommand("unblackchat", WithBlacklistMessage(handleUnblockChat))
	bot.OnCommand("whitechat", WithBlacklistMessage(handleUnblockChat))
	bot.OnCommand("unblchat", WithBlacklistMessage(handleUnblockChat))
	bot.OnCommand("unblockuser", WithBlacklistMessage(handleUnblockUser))
	bot.OnCommand("unblacklistuser", WithBlacklistMessage(handleUnblockUser))
	bot.OnCommand("unbluser", WithBlacklistMessage(handleUnblockUser))
	bot.OnCommand("whitelistuser", WithBlacklistMessage(handleUnblockUser))
	bot.OnCommand("autoleave", WithBlacklistMessage(autoLeaveHandler))
	bot.OnCommand("adminmode", WithBlacklistMessage(adminModeHandler))
	bot.OnCommand("cleanmode", WithBlacklistMessage(cleanModeHandler))
	bot.OnCommand("logger", WithBlacklistMessage(handleLogger))
	bot.OnCommand("playmode", WithBlacklistMessage(playmodeHandler))
	bot.OnCommand("autoplay", WithBlacklistMessage(autoplayHandler))
	bot.OnCommand("reload", WithBlacklistMessage(reloadHandler))
	bot.OnCommand("restart", WithBlacklistMessage(handleRestart))
	bot.OnCommand("settings", WithBlacklistMessage(settingsHandler))
	bot.OnCommand("stats", WithBlacklistMessage(statsHandler))
	bot.OnCommand("auth", WithBlacklistMessage(addAuthHandler))
	bot.OnCommand("addauth", WithBlacklistMessage(addAuthHandler))
	bot.OnCommand("authorize", WithBlacklistMessage(addAuthHandler))
	bot.OnCommand("delauth", WithBlacklistMessage(delAuthHandler))
	bot.OnCommand("unauth", WithBlacklistMessage(delAuthHandler))
	bot.OnCommand("delauthuser", WithBlacklistMessage(delAuthHandler))
	bot.OnCommand("authlist", WithBlacklistMessage(authListHandler))
	bot.OnCommand("authusers", WithBlacklistMessage(authListHandler))
	bot.OnCommand("privacy", WithBlacklistMessage(privacyHandler))
	bot.OnCommand("cmddelete", WithBlacklistMessage(cmdDeleteHandler))
	bot.OnCommand("commanddelete", WithBlacklistMessage(cmdDeleteHandler))
	bot.OnCommand("creload", WithBlacklistMessage(creloadHandler))
	bot.OnUpdateNewCallbackQuery(WithBlacklistCallback(broadcastCancelCB), callbackquery.Regex("^bcast_cancel$"))
	bot.OnUpdateNewCallbackQuery(WithBlacklistCallback(langCallbackHandler), callbackquery.Regex("^lang:(select|[a-z]{2})$"))
	bot.OnUpdateNewCallbackQuery(WithBlacklistCallback(restartConfirmHandler), callbackquery.Regex("^restart:(bot|replay)$"))
	bot.OnUpdateNewCallbackQuery(WithBlacklistCallback(settingsCallbackHandler), callbackquery.Regex("^set|info:"))
	bot.OnUpdateNewCallbackQuery(WithBlacklistCallback(startCB), callbackquery.Equal("start"))
	bot.OnUpdateNewCallbackQuery(WithBlacklistCallback(helpCB), callbackquery.Equal("help_cb"))
	bot.OnUpdateNewCallbackQuery(WithBlacklistCallback(helpCallbackHandler), callbackquery.Regex("^help:(.+)$"))
	bot.OnUpdateChatMember(handleParticipantUpdate, nil)
	bot.OnMessage(WithBlacklistMessage(handleActions), actionFilter)
	bot.OnUpdateFile(downloadUpdateHandler, nil)

	bot.OnUpdateChatReadOutbox(cleanModeReadHandler, nil)
	bot.OnUpdateNewCallbackQuery(WithBlacklistCallback(cancelHandler), callbackquery.Equal("cancel"))
	bot.OnUpdateNewCallbackQuery(WithBlacklistCallback(closeHandler), callbackquery.Equal("close"))
	bot.OnUpdateNewCallbackQuery(WithBlacklistCallback(roomHandle), callbackquery.Regex("^room:-?\\d+:\\w+$"))
	bot.OnUpdateNewCallbackQuery(WithBlacklistCallback(emptyCBHandler), callbackquery.Regex("progress"))
	bot.OnUpdateNewCallbackQuery(WithBlacklistCallback(autoplayCallbackHandler), callbackquery.Equal("autoplay:toggle"))

	assistants.ForEach(func(a *core.Assistant) {
		a.Ntg.OnStreamEnd(streamEndHandler)
	})

	go MonitorRooms()

	autoLeaveSvc.Start()
	cleanScheduler.start()

	if config.SetCmds && config.OwnerID != 0 {
		go setBotCommands(bot)
	}
}
