name: PyLint

on: [push, pull_request]

jobs:
    PEP8:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"
            - name: Install Python lint libraries
              run: |
                  pip install autoflake isort black
            - name: Remove unused imports and variables
              run: |
                  autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports .
            - name: lint with isort
              run: |
                  isort .
            - name: lint with black
              run: |
                  black --exclude "config\.py" .             
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              with:
                commit-message: Formate By @vivekkumar0708
                title: Format code
                body: Automated code formatting.
                labels: ⚫️ black
                branch: autofix
                committer: vivekkumar0708 <vivekkumar0708@users.noreply.github.com>
                author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
                signoff: true
                delete-branch: true