name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - "pyproject.toml"
      - "**.yml"

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: install
        run: pip install uv jq tomlkit

      - name: update
        id: update
        run: |
          uv sync --refresh

          python <<EOF
          import json
          from pathlib import Path
          import tomlkit

          pyproject_path = Path("pyproject.toml")
          outdated = json.loads(__import__("subprocess").check_output(
              ["uv", "pip", "list", "--outdated", "--format", "json"]
          ))

          doc = tomlkit.parse(pyproject_path.read_text())
          sections = [("project", "dependencies"), ("project", "optional-dependencies")]
          changed = 0

          for dep in outdated:
              name = dep["name"]
              latest = dep["latest_version"]
              for section, key in sections:
                  if section in doc and key in doc[section]:
                      deps = doc[section][key]
                      for i, d in enumerate(deps):
                          if isinstance(d, str) and d.lower().startswith(name.lower()):
                              new_dep = f"{name}=={latest}"
                              if deps[i] != new_dep:
                                  deps[i] = new_dep
                                  changed += 1

          pyproject_path.write_text(tomlkit.dumps(doc))

          title = "Update dependencies" if not changed else f"Update dependencies [{changed} packages]"
          with open("/tmp/title.txt", "w") as f:
              f.write(title)
          EOF

          uv lock

          echo "title=$(cat /tmp/title.txt)" >> $GITHUB_OUTPUT
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          git diff -U0 pyproject.toml | grep '^[+-][^+-]' >> $GITHUB_OUTPUT || true
          echo "EOF" >> $GITHUB_OUTPUT

      - name: pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update deps"
          title: ${{ steps.update.outputs.title }}
          body: |
            Updated dependencies:

            ```diff
            ${{ steps.update.outputs.diff }}
            ```
          branch: deps/update-pip-deps
          delete-branch: true
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"